plugins:
  bekcan_academic_profile_enabled:
    default: true
    client: true
  bekcan_academic_titles:
    default: "Profesör (Prof. Dr.)|Doçent (Doç. Dr.)|Doktor Öğretim Üyesi (Dr. Öğr. Üyesi)|Öğretim Görevlisi (Öğr. Gör.)|Araştırma Görevlisi (Arş. Gör.)|Uzman Doktor (Uzm. Dr.)|Doktora Öğrencisi / Adayı|Yüksek Lisans Mezunu / Öğrencisi"
    type: list
    client: true
  professor_auto_group_id:
    default: -1
    type: integer